spring.application.name=AI-Interview-Portal

# H2 Configuration (Embedded Database)
spring.datasource.url=jdbc:h2:mem:interview;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false
server.port=8096

spring.datasource.initialization-mode=always
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=trace

# Jdoodle credentials
jdoodle.clientId=2bd6debd97057201de33e29bd853b189
jdoodle.clientSecret=c5e4cf06204b3f0633ff308884f1363e1c09d7ab3254635188d95f30535be8e3
